// Generated by https://quicktype.io

export interface Tweet {
  retweeted: boolean;
  source: string;
  entities: Entities;
  display_text_range: string[];
  favorite_count: string;
  id_str: string;
  truncated: boolean;
  retweet_count: string;
  id: string;
  created_at: string;
  favorited: boolean;
  full_text: string;
  lang: string;
}

export interface Entities {
  hashtags: any[];
  symbols: any[];
  user_mentions: any[];
  urls: any[];
}
